title: The Goofball Theater
description: Beyond devious.

plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs


url: https://goofball.world.katiebuilds.website

color_scheme: discord

aux_links:
  Join: https://discord.gg/vXXFg2SKa7

callouts:
  notice:
    title: Notice
    color: yellow
  blurp:
    color: blurple

mermaid:
  version: "9.1.3"

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  elections:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    elections:
      # Give the collection a name
      name: Past Elections
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
