title: The Goofball Theater
description: Beyond devious.
theme: just-the-docs

url: https://goofball.world.katiebuilds.website

color_scheme: discord

aux_links:
  Join: https://discord.gg/vXXFg2SKa7

callouts:
  notice:
    title: Notice
    color: yellow
  blurp:
    color: blurple

mermaid:
  version: "9.1.3"